ARG BASE_IMAGE 
#=registry.opensource.zalan.do/library/alpine-3.15:latest
ARG VERSION=latest

FROM ${BASE_IMAGE}
ARG PACKAGER
LABEL maintainer="Opensource @ CYBERTEC <cpo-community@googlegroups.com>"

# We need root certificates to deal with teams api over https
RUN ${PACKAGER} -y update && ${PACKAGER} -y install ca-certificates && ${PACKAGER} clean all;

# RUN addgroup -g 1000 pgo
# RUN adduser -D -u 1000 -G pgo -g 'Postgres Operator' pgo

RUN groupadd -g 1000 cpo
RUN useradd cpo -u 1000 -g 1000

USER 1000:1000

COPY build/* /

ENTRYPOINT ["/cybertec-pg-operator"]
