ARG BASE_IMAGE 
#=registry.opensource.zalan.do/library/alpine-3.15:latest
ARG VERSION=latest

FROM arm64v8/${BASE_IMAGE} as builder
ARG PACKAGER
ARG VERSION

COPY  . /go/src/github.com/cybertec-postgresql/cybertec-pg-operator
WORKDIR /go/src/github.com/cybertec-postgresql/cybertec-pg-operator

ENV OPERATOR_LDFLAGS="-X=main.version=${VERSION}"

RUN ${PACKAGER} -y install --nodocs  https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && ${PACKAGER} -y update && ${PACKAGER} -y install dpkg wget && ${PACKAGER} clean all;

RUN bash docker/build_operator.sh

FROM arm64v8/${BASE_IMAGE}
ARG PACKAGER
LABEL maintainer="Opensource @ CYBERTEC <cpo-community@googlegroups.com>"

# We need root certificates to deal with teams api over https
RUN ${PACKAGER} -y update && ${PACKAGER} -y install ca-certificates && ${PACKAGER} clean all;
#RUN apk --no-cache add ca-certificates

COPY --from=builder /go/src/github.com/cybertec-postgresql/cybertec-pg-operator/build/* /

# RUN addgroup -g 1000 pgo
# RUN adduser -D -u 1000 -G pgo -g 'Postgres Operator' pgo

RUN groupadd -g 1000 cpo
RUN useradd cpo -u 1000 -g 1000

USER 1000:1000

ENTRYPOINT ["/postgres-operator"]
