name: operator-tests

on: 
  pull_request:
  push:
    branches:
    - main

jobs:
  tests:
    name: Unit tests and coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
          go-version: "^1.25.2"
    - name: Make dependencies
      run: make deps mocks
    - name: Compile
      run: make linux
    - name: Run unit tests
      run: go test -race -covermode atomic -coverprofile=coverage.out ./...
    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.9
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
